Fixed whole-repo to add config/config-file/queries keys and simplify the checkout

diff --git a/changes/action.yml b/changes/action.yml
--- a/changes/action.yml
+++ b/changes/action.yml
@@ -33,7 +33,7 @@ runs:
   using: 'composite'
   steps:
     - if: ${{ inputs.build-xml != '' || inputs.projects-json != '' || inputs.config-file != '' }}
-      name: Checkout project definition files and/or CodeQL config file
+      name: Checkout required files
       uses: actions/checkout@v4
       with:
         sparse-checkout: |
@@ -85,6 +85,14 @@ runs:
           const script = require(path.join(action_path, 'build-projects-from-xml.js'))
           return script(github, context, core)
 
+    - name: Check we have projects
+      id: check-projects
+      if: ${{ ! steps.read-projects.outputs.result && ! steps.build-projects.outputs.projects }}
+      run: |
+        echo "::error::No projects found"
+        exit 1
+      shell: bash
+
     - name: Debug build projects
       if: ${{ runner.debug == '1' }}
       run: echo "${result}"
@@ -94,6 +102,7 @@ runs:
 
     - name: Build filters
       id: build-filters
+      needs: check-projects
       uses: actions/github-script@v7
       env: 
         projects: ${{ steps.read-projects.outputs.result || steps.build-projects.outputs.projects }}
